FROM ubuntu:latest
RUN apt update && apt install -y binutils-arm-none-eabi gcc-arm-none-eabi python2 make && apt clean
RUN update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
CMD bash
