name: Build controller for cortex

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    container: jvastbinder/packetcraft_interview:build-packetcraft-controller

    steps:

    - uses: actions/checkout@v3
    - name: Run check
      run:  make -C controller/build/ble5-ctr/gcc/ CPU=cortex-m4

